### ISSUE TITLE
dataLayer.transaction Not Populating

### ISSUE THREAD

**Issue by jhambleton-sfdc** [TriggeredMessaging/digitalDataMagentoExtension#6]
I noticed on my confirmation page that dataLayer.transaction isn't being populated. All other dataLayer objects are being populated (e.g. page, user) but not the transaction object. I spent some time troubleshooting this and narrowed it down to:

protected function _getSalesOrder() {
    return Mage::getModel('sales/order');
  }

For some reason this method isn't returning the order object, even though the orderID is valid. I tried further modifying this method by hard-coding a known orderID:

protected function _getSalesOrder() {
    return Mage::getModel('sales/order')->load('250');
  }

However, this still didn't return the order object. Has this issue come up before or any thoughts? It's been a great extension otherwise but having that transaction info on the confirmation page is pretty important.

**Comment by dhendo** [comment]
@justinhambleton Thanks, we'll take a look

**Comment by justinhambleton** [comment]
@dhendo Thanks. BTW - I'm using CE 1.9

**Comment by dhendo** [comment]
@justinhambleton We've taken a look at our test stores (pretty much vanilla Magento installs), and this works OK for us. Is there anything special about the sites you're trying?

Some questions:
- Was the transaction object missing in the output DDL, or were the values blank?
(Try looking around https://github.com/TriggeredMessaging/digitalDataMagentoExtension/blob/master/app/code/community/TriggeredMessaging/DigitalDataLayer/Model/Page/Observer.php#L1033 - is orderId coming back? Try logging the exception handler in _setTransaction

**Comment by justinhambleton** [comment]
@dhendo - I'll take a look at that today. I have two fairly vanilla Magento environments set-up and both are exhibiting this behavior. I haven't done anything special with the exception of:

1) After installing the TriggeredMessaging extension, Magento Admin was broken. I narrowed this down to a section of system.xml. This particular node was causing Magento to throw an exception:

<TriggeredMessaging_DigitalDataLayer_Attributes_Enabled translate="label">
...
</TriggeredMessaging_DigitalDataLayer_Attributes_Enabled>

I commented this out through SSH and Magento Admin was working again. Perhaps related to this is the following "file" which, for some reason, is being treated as a folder:
app/code/commmunity/TriggeredMessaging/DigitalDataLayer/Model/System/Config/Source/Productattributes.php

I'm on an Ubuntu/Apache2 stack and for whatever reason, that particular file is being treated as a folder after installing the TriggeredMessaging extension. I haven't quite figured out how to make this file seen as an actual file rather than a folder. You can see this in the screenshot below:

![file_as_folder](https://cloud.githubusercontent.com/assets/5438708/6289072/27c3d6e8-b8e3-11e4-8a3d-1cc7f9c0f278.png)

![screen shot 2015-02-20 at 9 34 21 am](https://cloud.githubusercontent.com/assets/5438708/6289164/b324668a-b8e3-11e4-9be9-af5d2744bde6.png)

**Comment by dhendo** [comment]
Hi Justin,

Did you reach out to use before via the Magento messaging system as SignalDev?

It looks like it may be an issue relating to the unzipping, where magento decides to treat thins as a folder rather than a file: http://stackoverflow.com/questions/15751812/manual-installation-of-magento-extension-turns-every-file-into-a-folder

**Comment by justinhambleton** [comment]
Yes, that was me :)

I uninstalled the TriggeredMessaging extention and applied the Magento Downloaded fix described above and that definitely fixed the initial error in Magento Admin and now the Productattributes.php file is in fact a file. Thank you! I would not have figured that out on my own.

Unfortunately, the transaction object is still not being returned on the order confirmation page so I'll dig into that to see if I can get the exception. Thanks again for the help thus far.

**Comment by justinhambleton** [comment]
Unfortunately, the transaction object still isn't returning. However, I did notice something odd when comparing different scenarios. On the order confirmation page (onepage/success) I noticed that when the transaction object isn't returned, I see this in the page object: "category":{"pageType":"basket"}

The one time the transaction object was returned, it looked like this: "category":{"pageType":"confirmation"}

The very first order I placed in a fresh Magento environment showed: {"pageType":"confirmation"}

Now, every subsequent order that is placed, whether it's a new user or an existing registered user, shows: {"pageType":"basket"}

I'll trace down the logic to see what's happening there. That may hold the clue :)

**Comment by justinhambleton** [comment]
Problem resolved. Magento onepage checkout uses the Prototype framework so, while the digitalData.transaction object is actually being created and populated on order success, the page source doesn't actually change because, Prototype :)

This was a rookie mistake. As soon as I started poking around in the Chrome-->Developer Tools--Console I was able to verify the transaction object was created and accessible. Lesson learned: don't rely on page source :)

Thanks again for the earlier help. This is a great extension.

**Comment by dhendo** [comment]
@justinhambleton Great news, glad you figured it out! If you don't mind, can you drop me an email with how you guys are using it / planning to use it? Mainly to satisfy my curiosity and to plan any future directions it may need to head towards.

**Comment by justinhambleton** [comment]
I sure will!
